#35: Added regular reporting of metrics from EXA_SYSTEM_EVENTS
exasol/cloudwatch-adapter pull request #36
Opened 2021-02-18 09:41 UTC by jakobbraun

Closes #35

2021-02-18 09:43 UTC, jakobbraun commented
left open: https://github.com/exasol/cloudwatch-adapter/issues/37

2021-02-18 12:07 UTC, morazow requested changes

2021-02-18 12:07 UTC, morazow commented on src/main/java/com/exasol/cloudwatch/AbstractExasolStatisticsTableMetricReader.java
> +     * {@link #schemaOverride} was set this schema is returned.
```suggestion
     * Get the injection free schema name. Typically this is {@code EXA_STATISTICS}, it is different only when {@link #schemaOverride} is set in the constructor.
```

2021-02-18 12:07 UTC, morazow commented on src/main/java/com/exasol/cloudwatch/AbstractExasolStatisticsTableMetricReader.java
> +     * {@link #schemaOverride} was set this schema is returned.
Please correct the formatting.

2021-02-19 07:19 UTC, jakobbraun commented on src/main/java/com/exasol/cloudwatch/AbstractExasolStatisticsTableMetricReader.java
> +    protected abstract List<ExasolMetricDatum> loadMetricsForTable(final List<ExasolStatisticsTableMetric> metrics,
it's the interface to the different implementations of this class.

2021-02-19 07:42 UTC, morazow approved these changes
Minor typo, then approved.

2021-02-19 07:42 UTC, morazow commented on src/main/java/com/exasol/cloudwatch/MainExasolMetricReader.java
> +     * loadMetricsForTable Create a new instance of {@link MainExasolMetricReader}.
```suggestion
     * Create a new instance of {@link MainExasolMetricReader}.
```

2021-02-19 07:44 UTC, morazow approved these changes

2021-02-19 08:00 UTC, merged