#39: Refactored the exasol metric class structure
exasol/cloudwatch-adapter pull request #40
Opened 2021-02-23 11:00 UTC by jakobbraun

Closes #39

2021-02-24 08:27 UTC, morazow requested changes

2021-02-24 08:27 UTC, morazow commented on src/main/java/com/exasol/cloudwatch/exasolmetrics/CompoundExasolMetricReader.java
> +    public List<ExasolMetricDatum> readMetrics(final Collection<String> metrics, final Instant ofMinute) {
I think we should refactor this method.

You can delegate `filter` method to the factories, union results and check if all `metrics` covered.

2021-03-01 09:31 UTC, jakobbraun commented on src/test/java/com/exasol/cloudwatch/configuration/EnvironmentConfigurationReaderTest.java
> +        assertThat(READER.readEnabledMetrics(AVAILABLE_METRICS),
make more clear that env var is undefined

2021-03-01 12:12 UTC, morazow approved these changes

2021-03-01 12:50 UTC, merged